FROM python:3.12-slim

WORKDIR /app
COPY worker/requirements.txt worker/requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt

ENV CLASSIFICATION_PROMPT_PATH=/prompts/clothing_classifier_prompt.txt
COPY worker/app.py worker/local_worker.py worker/test_app.py ./
COPY worker/prompts/clothing_classifier_prompt.txt /prompts/clothing_classifier_prompt.txt
CMD ["python", "local_worker.py"]
